---

# To start: ansible-playbook main.yml --limit "am-scr-001" -i ~/Documents/github/ansible-admin/playbooks/opensips/hosts

- name: OpenSIPS installation by sources compilation
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    - templatesdir: "./templates"

  vars_files:
    - vars/main.yml

  handlers:
    - include: 'handlers/main.yml'

  pre_tasks:
    - name: Verify Ansible version requirements.
      assert:
        that: "ansible_version.full | version_compare('2.1', '>=')"
        msg: >
          "You must update Ansible to at least 2.1"
  tasks:
    - name: Include task list in play
      include: "tasks/main.yml"
