---
- name: Choose mysql variable for Debian/Sretch
  set_fact:
    mysql_package: 'default-libmysqlclient-dev'
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'stretch'

- name: Choose mysql variable for Debian/Jessie
  set_fact:
    mysql_package: 'libmysqlclient-dev'
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie'

- debug:
    msg: "Mysql package is {{ mysql_package }} for {{ ansible_distribution }}/{{ ansible_distribution_version }}"

- name: Install Prerequisites OpenSIPS packages
  package:
    name: "{{ opensips_packages }}"
    state: present
  register: task_result
  until: task_result is succeeded
  retries: 10
  delay: 1

- name: Create OpenSIPS Group
  group: "name={{ opensips_group }} state=present"

- name: Add OpenSIPS User
  user: "name={{ opensips_user }} comment='OpenSIPS process user' shell=/sbin/nologin group={{ opensips_group }}"

- name: Git clone OpenSIPS
  git:
    repo: https://github.com/OpenSIPS/opensips.git
    dest: /usr/local/src/opensips-{{ opensips_version }}
    clone: yes
    version: "{{ opensips_version }}"

- name: Running make for OpenSIPS
  make:
    chdir: "{{ item.chdir }}"
    target: "{{ item.target }}"
    params:
      prefix: "{{ item.prefix }}"
      include_modules: "{{ opensips_modules }}"
  with_items:
    - { chdir: '/usr/local/src/opensips-{{ opensips_version }}', target: 'modules', prefix: '/usr/local'}
    - { chdir: '/usr/local/src/opensips-{{ opensips_version }}', target: 'install', prefix: '/usr/local'}


- name: Set ownership on important directories for the OpenSIPS user
  file: "path={{ item.path }} owner={{ opensips_user }} group={{ opensips_group }} recurse=yes"
  with_items:
    - { path: '/usr/local/etc/opensips/' }

- name: Create OpenSIPS service file
  copy:
    src: /usr/local/src/opensips-{{ opensips_version }}/packaging/debian/opensips.service
    dest: "/etc/systemd/system/opensips.service"
    remote_src: yes
  notify:
    - Change Config opensips.service

- name: Create OpenSIPS default file
  copy:
    src: /usr/local/src/opensips-{{ opensips_version }}/packaging/debian/opensips.default
    dest: "/etc/default/opensips"
    remote_src: yes
  notify:
    - Change Config opensips.default

- name: Copy opensips-m4cfg
  copy:
    src: /usr/local/src/opensips-{{ opensips_version }}/packaging/debian/opensips-m4cfg
    dest: "/usr/local/sbin/opensips-m4cfg"
    mode: 0744
    remote_src: yes
  notify:
    - Change Config opensips-m4cfg

- name: reload systemd
  systemd:
    daemon_reload: yes

- debug:
    msg: "You can start opensips with : service opensips start"
